apiVersion: 1

providers:
  - name: VoxFlow Dashboards
    orgId: 1
    folder: VoxFlow
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
