spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8089/realms/voxflow-realm}

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

